#!/usr/bin/env bash
#
# boost_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

BOOST_VERSION_1="1.73.0"
BOOST_VERSION_2="1_73_0"
SHA256="9995e192e68528793755692917f9eb6422f3052a53c5e13ba278a228af6c7acf"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi
cd "${MY_PATH}/../Sources"

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode

export MACOSX_DEPLOYMENT_TARGET=10.9
export MIN_SUPPORTED_MACOSX_DEPLOYMENT_TARGET=10.9
rm -rf "boost_"*
get_src_and_verify_checksum "boost_${BOOST_VERSION_2}.tar.gz" "${SHA256}" "https://dl.bintray.com/boostorg/release/${BOOST_VERSION_1}/source/boost_${BOOST_VERSION_2}.tar.gz"
tar xf "${MY_PATH}/../Sources/archives/boost_${BOOST_VERSION_2}.tar.gz" -C .
cd "boost_${BOOST_VERSION_2}"
rm -rf "stage"
./bootstrap.sh --with-libraries=chrono,filesystem,iostreams,locale,program_options,random,regex,system,timer,test,thread --with-toolset=clang
./b2 threading=multi --layout=tagged link=shared variant=release -sNO_LZMA=1 -sNO_ZSTD=1 cxxstd=14
cd "stage/lib"
mkdir "boost_${BOOST_VERSION_2}-RELEASE"
cp *.dylib "boost_${BOOST_VERSION_2}-RELEASE"
cd "boost_${BOOST_VERSION_2}-RELEASE"
for filename in * ; do
  install_name_tool -id "@rpath/${filename}" "${filename}"
  edit_dylib_deps "${filename}"
done
cd "${MY_PATH}/../"
rm -rf "CompiledLibs/boost_"*
mv "Sources/boost_${BOOST_VERSION_2}/stage/lib/boost_${BOOST_VERSION_2}-RELEASE" "CompiledLibs/boost_${BOOST_VERSION_2}-RELEASE"
rm -rf "../Headers/boost"
cp -rf "Sources/boost_${BOOST_VERSION_2}/boost" "../Headers/"
rm -rf "../lib/libboost"*
cp -rf "CompiledLibs/boost_${BOOST_VERSION_2}-RELEASE/"* "../lib/"

echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo