#!/usr/bin/env bash
#
# boost_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

BOOST_VERSION_1="1.74.0"
BOOST_VERSION_2="1_74_0"
SHA256="afff36d392885120bcac079148c177d1f6f7730ec3d47233aa51b0afa4db94a5"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode

cd "${SOURCES_PATH}"
export MACOSX_DEPLOYMENT_TARGET=10.9
export MIN_SUPPORTED_MACOSX_DEPLOYMENT_TARGET=10.9
rm -rf "boost"*
get_src_and_verify_checksum "boost_${BOOST_VERSION_2}.tar.gz" "${SHA256}" "https://dl.bintray.com/boostorg/release/${BOOST_VERSION_1}/source/boost_${BOOST_VERSION_2}.tar.gz"
tar xf "${SOURCES_PATH}/archives/boost_${BOOST_VERSION_2}.tar.gz" -C .
ln -s "boost_${BOOST_VERSION_2}" "boost"
cd "boost"
rm -rf "stage"
./bootstrap.sh --with-libraries=chrono,filesystem,iostreams,locale,program_options,random,regex,system,timer,test,thread --with-toolset=clang
./b2 threading=multi --layout=tagged link=shared variant=release -sNO_LZMA=1 -sNO_ZSTD=1 cxxstd=14
cd "stage/lib"
mkdir "boost_${BOOST_VERSION_2}-RELEASE"
cp *".dylib" "boost_${BOOST_VERSION_2}-RELEASE"
cd "boost_${BOOST_VERSION_2}-RELEASE"
for filename in * ; do
  install_name_tool -id "@rpath/${filename}" "${filename}"
  edit_dylib_deps "${filename}"
done
rm -rf "${LIBS_PATH}/libboost"*
cp -rf * "${LIBS_PATH}/"
rm -rf "${HEADERS_PATH}/boost"
cp -rf "${SOURCES_PATH}/boost/boost" "${HEADERS_PATH}/"
echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo