#!/usr/bin/env bash
#
# cairo_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

CAIRO_VERSION="1.16.0"
SHA256="5e7b29b3f113ef870d1e3ecf8adf21f923396401604bda16d44be45e66052331"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi
cd "${MY_PATH}/../Sources"

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode
check_pixman
check_fontconfig
check_freetype
check_libpng
check_libffi

rm -rf "cairo-"*
get_src_and_verify_checksum "cairo-${CAIRO_VERSION}.tar.xz" "${SHA256}" "https://cairographics.org/releases/cairo-${CAIRO_VERSION}.tar.xz"
tar xf "${SOURCES_PATH}/archives/cairo-${CAIRO_VERSION}.tar.xz" -C .
ln -s "cairo-${CAIRO_VERSION}" "cairo"
cd "cairo"
./configure --disable-dependency-tracking --enable-gobject=yes --enable-svg=yes --enable-tee=yes --enable-quartz-image --enable-xcb=no --enable-xlib=no --enable-xlib-xrender=no
make
mkdir "cairo-${CAIRO_VERSION}-RELEASE"
cp "src/.libs/libcairo.2.dylib" "cairo-${CAIRO_VERSION}-RELEASE/libcairo.2.dylib"
cd "cairo-${CAIRO_VERSION}-RELEASE"
install_name_tool -id "@rpath/libcairo.2.dylib" "libcairo.2.dylib"
edit_dylib_deps "libcairo.2.dylib"
rm -rf "${LIBS_PATH}/libcairo.2.dylib" "${LIBS_PATH}/libcairo.dylib"
cp -rf "libcairo.2.dylib" "${LIBS_PATH}/libcairo.2.dylib"
ln -s "libcairo.2.dylib" "${LIBS_PATH}/libcairo.dylib"
rm -rf "${HEADERS_PATH}/cairo"
mkdir "${HEADERS_PATH}/cairo"
cp "${SOURCES_PATH}/cairo/cairo-version.h" "${HEADERS_PATH}/cairo/"
cp "${SOURCES_PATH}/cairo/util/cairo-gobject/cairo-gobject.h" "${HEADERS_PATH}/cairo/"
cp "${SOURCES_PATH}/cairo/util/cairo-script/cairo-script-interpreter.h" "${HEADERS_PATH}/cairo/"
cd "${SOURCES_PATH}/cairo/src"
cp "cairo-deprecated.h" "cairo-features.h" "cairo-ft.h" "cairo-pdf.h" "cairo-ps.h" "cairo-script.h" "cairo-svg.h" "cairo-tee.h" "cairo-xcb.h" "cairo-xlib-xrender.h" "cairo-xlib.h" "cairo-xml.h" "cairo.h" "${HEADERS_PATH}/cairo/"
echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo