#!/usr/bin/env bash
#
# fontconfig_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

FONTCONFIG_VERSION="2.13.1"
SHA256="9f0d852b39d75fc655f9f53850eb32555394f36104a044bb2b2fc9e66dbbfa7f"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode
check_freetype

cd "${SOURCES_PATH}"
rm -rf "fontconfig"*
get_src_and_verify_checksum "fontconfig-${FONTCONFIG_VERSION}.tar.gz" "${SHA256}" "https://www.freedesktop.org/software/fontconfig/release/fontconfig-${FONTCONFIG_VERSION}.tar.gz"
tar xf "${SOURCES_PATH}/archives/fontconfig-${FONTCONFIG_VERSION}.tar.gz" -C .
ln -s "fontconfig-${FONTCONFIG_VERSION}" "fontconfig"
cd "fontconfig"
patch -b < "${SCRIPTS_PATH}/fontconfig.patch"
./configure --disable-docs --disable-dependency-tracking --disable-silent-rules --enable-shared --with-add-fonts="/System/Library/Fonts","/Library/Fonts","~/Library/Fonts"
make
mkdir "fontconfig-${FONTCONFIG_VERSION}-RELEASE"
cp "src/.libs/libfontconfig.1.dylib" "fontconfig-${FONTCONFIG_VERSION}-RELEASE/libfontconfig.1.dylib"
cd "fontconfig-${FONTCONFIG_VERSION}-RELEASE"
install_name_tool -id "@rpath/libfontconfig.1.dylib" "libfontconfig.1.dylib"
edit_dylib_deps "libfontconfig.1.dylib"
rm -rf "${LIBS_PATH}/libfontconfig.1.dylib" "${LIBS_PATH}/libfontconfig.dylib"
cp -rf "libfontconfig.1.dylib" "${LIBS_PATH}/libfontconfig.1.dylib"
ln -s "libfontconfig.1.dylib" "${LIBS_PATH}/libfontconfig.dylib"
rm -rf "${HEADERS_PATH}/fontconfig"
mkdir "${HEADERS_PATH}/fontconfig"
cp -rf "${SOURCES_PATH}/fontconfig/fontconfig/fontconfig.h" "${HEADERS_PATH}/fontconfig/fontconfig.h"
echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo