#!/usr/bin/env bash
#
# fontconfig_build
# Martin Hrubý (hrubymar10), 2018-2024
#

set -e

FONTCONFIG_VERSION="2.15.0"
SHA256="63a0658d0e06e0fa886106452b58ef04f21f58202ea02a94c39de0d3335d7c0e"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_freetype
check_pkg_config

cd "${SOURCES_PATH}"
rm -rf "fontconfig"*
get_src_and_verify_checksum "fontconfig-${FONTCONFIG_VERSION}.tar.xz" "${SHA256}" "https://www.freedesktop.org/software/fontconfig/release/fontconfig-${FONTCONFIG_VERSION}.tar.xz"
tar xf "${SOURCES_PATH}/archives/fontconfig-${FONTCONFIG_VERSION}.tar.xz" -C .
cp -R "fontconfig-${FONTCONFIG_VERSION}" "fontconfig-${FONTCONFIG_VERSION}-arm64"
mv "fontconfig-${FONTCONFIG_VERSION}" "fontconfig-${FONTCONFIG_VERSION}-x86_64"
ln -s "fontconfig-${FONTCONFIG_VERSION}-x86_64" "fontconfig"

# Build x86_64
cd "${SOURCES_PATH}/fontconfig-${FONTCONFIG_VERSION}-x86_64"
source "${MY_PATH}/env"
export LDFLAGS="${LDFLAGS_X86_64}"
export CFLAGS="${CFLAGS_X86_64}"
export CXXFLAGS="${CXXFLAGS_X86_64}"
./configure --disable-docs --disable-dependency-tracking --disable-silent-rules --enable-shared --with-add-fonts="/System/Library/Fonts","/Library/Fonts","~/Library/Fonts" --host=x86_64-apple-darwin
make

# Build arm64
cd "${SOURCES_PATH}/fontconfig-${FONTCONFIG_VERSION}-arm64"
source "${MY_PATH}/env"
export LDFLAGS="${LDFLAGS_ARM64}"
export CFLAGS="${CFLAGS_ARM64}"
export CXXFLAGS="${CXXFLAGS_ARM64}"
./configure --disable-docs --disable-dependency-tracking --disable-silent-rules --enable-shared --with-add-fonts="/System/Library/Fonts","/Library/Fonts","~/Library/Fonts" --host=aarch64-apple-darwin
make

mkdir "fontconfig-${FONTCONFIG_VERSION}-RELEASE"
cd "fontconfig-${FONTCONFIG_VERSION}-RELEASE"
lipo -create "${SOURCES_PATH}/fontconfig-${FONTCONFIG_VERSION}-arm64/src/.libs/libfontconfig.1.dylib" "${SOURCES_PATH}/fontconfig-${FONTCONFIG_VERSION}-x86_64/src/.libs/libfontconfig.1.dylib" -output "libfontconfig.1.dylib"
install_name_tool -id "@rpath/libfontconfig.1.dylib" "libfontconfig.1.dylib"
rm -rf "${LIBS_PATH}/libfontconfig.1.dylib" "${LIBS_PATH}/libfontconfig.dylib"
cp -rf "libfontconfig.1.dylib" "${LIBS_PATH}/libfontconfig.1.dylib"
ln -s "libfontconfig.1.dylib" "${LIBS_PATH}/libfontconfig.dylib"
rm -rf "${HEADERS_PATH}/fontconfig"
mkdir "${HEADERS_PATH}/fontconfig"
cp -rf "${SOURCES_PATH}/fontconfig/fontconfig/fontconfig.h" "${HEADERS_PATH}/fontconfig/fontconfig.h"
generate_pkgconfig_file "fontconfig" "${FONTCONFIG_VERSION}"
echo "==> DONE ..."
echo ""
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo ""
