#!/usr/bin/env bash
#
# freetype_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

FREETYPE_VERSION="2.10.4"
SHA256="5eab795ebb23ac77001cfb68b7d4d50b5d6c7469247b0b01b2c953269f658dac"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode
check_libpng

cd "${SOURCES_PATH}"
rm -rf "freetype"*
get_src_and_verify_checksum "freetype-${FREETYPE_VERSION}.tar.gz" "${SHA256}" "https://download.savannah.gnu.org/releases/freetype/freetype-${FREETYPE_VERSION}.tar.gz"
tar xf "${SOURCES_PATH}/archives/freetype-${FREETYPE_VERSION}.tar.gz" -C .
ln -s "freetype-${FREETYPE_VERSION}" "freetype"
cd "freetype"
./autogen.sh
./configure --with-harfbuzz=no --with-brotli=no --enable-shared
make
mkdir "freetype-${FREETYPE_VERSION}-RELEASE"
cp "objs/.libs/libfreetype.6.dylib" "freetype-${FREETYPE_VERSION}-RELEASE/libfreetype.6.dylib"
cd "freetype-${FREETYPE_VERSION}-RELEASE"
install_name_tool -id "@rpath/libfreetype.6.dylib" "libfreetype.6.dylib"
edit_dylib_deps "libfreetype.6.dylib"
rm -rf "${LIBS_PATH}/libfreetype.6.dylib" "${LIBS_PATH}/libfreetype.dylib"
cp -rf "libfreetype.6.dylib" "${LIBS_PATH}/libfreetype.6.dylib"
ln -s "libfreetype.6.dylib" "${LIBS_PATH}/libfreetype.dylib"
echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo