#!/usr/bin/env bash
#
# fribidi_build
# Martin Hrubý (hrubymar10), 2020
#

set -e

FRIBIDI_VERSION="1.0.10"
SHA256="7f1c687c7831499bcacae5e8675945a39bacbad16ecaa945e9454a32df653c01"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode

cd "${SOURCES_PATH}"
rm -rf "fribidi"*
get_src_and_verify_checksum "fribidi-${FRIBIDI_VERSION}.tar.xz" "${SHA256}" "https://github.com/fribidi/fribidi/releases/download/v${FRIBIDI_VERSION}/fribidi-${FRIBIDI_VERSION}.tar.xz"
tar xf "${SOURCES_PATH}/archives/fribidi-${FRIBIDI_VERSION}.tar.xz" -C .
ln -s "fribidi-${FRIBIDI_VERSION}" "fribidi"
cd "fribidi"
./configure --disable-debug --disable-dependency-tracking --disable-silent-rules --enable-shared
make
mkdir "fribidi-${FRIBIDI_VERSION}-RELEASE"
cp "lib/.libs/libfribidi.0.dylib" "fribidi-${FRIBIDI_VERSION}-RELEASE/libfribidi.0.dylib"
cd "fribidi-${FRIBIDI_VERSION}-RELEASE"
install_name_tool -id "@rpath/libfribidi.0.dylib" "libfribidi.0.dylib"
edit_dylib_deps "libfribidi.0.dylib"
rm -rf "${LIBS_PATH}/libfribidi.0.dylib" "${LIBS_PATH}/libfribidi.dylib"
cp -rf "libfribidi.0.dylib" "${LIBS_PATH}/libfribidi.0.dylib"
ln -s "libfribidi.0.dylib" "${LIBS_PATH}/libfribidi.dylib"
echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo