#!/usr/bin/env bash
#
# fribidi_build
# Martin Hrubý (hrubymar10), 2020-2022
#

set -e

FRIBIDI_VERSION="1.0.12"
SHA256="0cd233f97fc8c67bb3ac27ce8440def5d3ffacf516765b91c2cc654498293495"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget

cd "${SOURCES_PATH}"
rm -rf "fribidi"*
get_src_and_verify_checksum "fribidi-${FRIBIDI_VERSION}.tar.xz" "${SHA256}" "https://github.com/fribidi/fribidi/releases/download/v${FRIBIDI_VERSION}/fribidi-${FRIBIDI_VERSION}.tar.xz"
tar xf "${SOURCES_PATH}/archives/fribidi-${FRIBIDI_VERSION}.tar.xz" -C .
cp -R "fribidi-${FRIBIDI_VERSION}" "fribidi-${FRIBIDI_VERSION}-arm64"
ln -s "fribidi-${FRIBIDI_VERSION}" "fribidi"
cd "fribidi"
# Build x86_64
source "${MY_PATH}/env"
export LDFLAGS="${LDFLAGS_X86_64}"
export CFLAGS="${CFLAGS_X86_64}"
export CXXFLAGS="${CXXFLAGS_X86_64}"
./configure --disable-debug --disable-dependency-tracking --disable-silent-rules --enable-shared --host=x86_64-apple-darwin
make
# Build arm64
cd "${SOURCES_PATH}/fribidi-${FRIBIDI_VERSION}-arm64"
source "${MY_PATH}/env"
export LDFLAGS="${LDFLAGS_ARM64}"
export CFLAGS="${CFLAGS_ARM64}"
export CXXFLAGS="${CXXFLAGS_ARM64}"
./configure --disable-debug --disable-dependency-tracking --disable-silent-rules --enable-shared --host=aarch64-apple-darwin
make
mkdir "fribidi-${FRIBIDI_VERSION}-RELEASE"
cd "fribidi-${FRIBIDI_VERSION}-RELEASE"
lipo -create "${SOURCES_PATH}/fribidi-${FRIBIDI_VERSION}-arm64/lib/.libs/libfribidi.0.dylib" "${SOURCES_PATH}/fribidi-${FRIBIDI_VERSION}/lib/.libs/libfribidi.0.dylib" -output "libfribidi.0.dylib"
install_name_tool -id "@rpath/libfribidi.0.dylib" "libfribidi.0.dylib"
rm -rf "${LIBS_PATH}/libfribidi.0.dylib" "${LIBS_PATH}/libfribidi.dylib"
cp -rf "libfribidi.0.dylib" "${LIBS_PATH}/libfribidi.0.dylib"
ln -s "libfribidi.0.dylib" "${LIBS_PATH}/libfribidi.dylib"
generate_pkgconfig_file "fribidi" "${FRIBIDI_VERSION}"
echo "==> DONE ..."
echo ""
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo ""
