#!/usr/bin/env bash
#
# gettext_build
# Martin Hrubý (hrubymar10), 2018-2023
#

set -e

GETTEXT_VERSION="0.22.4"
SHA256="29217f1816ee2e777fa9a01f9956a14139c0c23cc1b20368f06b2888e8a34116"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_gsed

cd "${SOURCES_PATH}"
rm -rf "gettext"*
get_src_and_verify_checksum "gettext-${GETTEXT_VERSION}.tar.xz" "${SHA256}" "https://ftp.gnu.org/pub/gnu/gettext/gettext-${GETTEXT_VERSION}.tar.xz"
tar xf "${SOURCES_PATH}/archives/gettext-${GETTEXT_VERSION}.tar.xz" -C .
cp -R "gettext-${GETTEXT_VERSION}" "gettext-${GETTEXT_VERSION}-arm64"
mv "gettext-${GETTEXT_VERSION}" "gettext-${GETTEXT_VERSION}-x86_64"
ln -s "gettext-${GETTEXT_VERSION}-x86_64" "gettext"

# Build x86_64
cd "${SOURCES_PATH}/gettext-${GETTEXT_VERSION}-x86_64"
source "${MY_PATH}/env"
export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
export LDFLAGS="${LDFLAGS_X86_64}"
export CFLAGS="${CFLAGS_X86_64}"
export CXXFLAGS="${CXXFLAGS_X86_64}"
arch -x86_64 ./configure --disable-dependency-tracking --enable-shared --disable-java --disable-csharp --disable-debug --disable-silent-rules --host=x86_64-apple-darwin
arch -x86_64 make MAKEINFO=true

# Build arm64
cd "${SOURCES_PATH}/gettext-${GETTEXT_VERSION}-arm64"
source "${MY_PATH}/env"
export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
export LDFLAGS="${LDFLAGS_ARM64}"
export CFLAGS="${CFLAGS_ARM64}"
export CXXFLAGS="${CXXFLAGS_ARM64}"
arch -arm64 ./configure --disable-dependency-tracking --enable-shared --disable-java --disable-csharp --disable-debug --disable-silent-rules --host=aarch64-apple-darwin
arch -arm64 make MAKEINFO=true

mkdir "gettext-${GETTEXT_VERSION}-RELEASE"
cd "gettext-${GETTEXT_VERSION}-RELEASE"
lipo -create "${SOURCES_PATH}/gettext-${GETTEXT_VERSION}-arm64/gettext-runtime/intl/.libs/libintl.8.dylib" "${SOURCES_PATH}/gettext-${GETTEXT_VERSION}-x86_64/gettext-runtime/intl/.libs/libintl.8.dylib" -output "libintl.8.dylib"
install_name_tool -id "@rpath/libintl.8.dylib" "libintl.8.dylib"
rm -rf "${LIBS_PATH}/libintl.8.dylib" "${LIBS_PATH}/libintl.dylib"
cp "libintl.8.dylib" "${LIBS_PATH}/libintl.8.dylib"
ln -s "libintl.8.dylib" "${LIBS_PATH}/libintl.dylib"
rm -rf "${HEADERS_PATH}/libintl.h"
cp "${SOURCES_PATH}/gettext/gettext-runtime/intl/libintl.h" "${HEADERS_PATH}/libintl.h"
echo "==> DONE ..."
echo ""
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo ""
