#!/usr/bin/env bash
#
# glib_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

GLIB_VERSION="2.64.4"
GLIB_VERSION_SHORT="2.64"
SHA256="f7e0b325b272281f0462e0f7fff25a833820cac19911ff677251daf6d87bce50"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi
cd "${MY_PATH}/../Sources"

source "${MY_PATH}/env"
source "${MY_PATH}/functions"
unset MACOSX_DEPLOYMENT_TARGET

check_wget
check_xcode
check_meson
check_ninja
check_pcre
check_libffi
check_gettext

rm -rf "glib-"*
get_src_and_verify_checksum "glib-${GLIB_VERSION}.tar.xz" "${SHA256}" "https://download.gnome.org/sources/glib/${GLIB_VERSION_SHORT}/glib-${GLIB_VERSION}.tar.xz"
tar xf "${MY_PATH}/../Sources/archives/glib-${GLIB_VERSION}.tar.xz" -C .
cd "glib-${GLIB_VERSION}"
mkdir "build"
meson -Dbsymbolic_functions=false -Ddtrace=false -Diconv=auto --default-library=shared --buildtype=release . "build"
cd "build"
ninja
mkdir "glib-${GLIB_VERSION}-RELEASE"
cp "glib/libglib-2.0.0.dylib" "glib-${GLIB_VERSION}-RELEASE/libglib-2.0.0.dylib"
cp "gmodule/libgmodule-2.0.0.dylib" "glib-${GLIB_VERSION}-RELEASE/libgmodule-2.0.0.dylib"
cp "gobject/libgobject-2.0.0.dylib" "glib-${GLIB_VERSION}-RELEASE/libgobject-2.0.0.dylib"
cp "gthread/libgthread-2.0.0.dylib" "glib-${GLIB_VERSION}-RELEASE/libgthread-2.0.0.dylib"
cp "gio/libgio-2.0.0.dylib" "glib-${GLIB_VERSION}-RELEASE/libgio-2.0.0.dylib"
cd "glib-${GLIB_VERSION}-RELEASE"
# TODO: Use MCS' pcre, libffi and gettext
for filename in * ; do
  install_name_tool -id "@rpath/${filename}" "${filename}"
  edit_dylib_deps "${filename}"
  remove_rpath_if_exists "${filename}" "@loader_path/../glib"
  remove_rpath_if_exists "${filename}" "@loader_path/../gmodule"
  remove_rpath_if_exists "${filename}" "@loader_path/../gobject"
  remove_rpath_if_exists "${filename}" "/usr/local/Cellar/pcre/"
  remove_rpath_if_exists "${filename}" "/usr/local/Cellar/libffi/"
done
cd "${MY_PATH}/../"
rm -rf "CompiledLibs/glib-"*
mv "Sources/glib-${GLIB_VERSION}/build/glib-${GLIB_VERSION}-RELEASE" "CompiledLibs/glib-${GLIB_VERSION}-RELEASE"
rm -rf "../Headers/glib"*
mkdir -p "../Headers/glib-2.0/gio"
mkdir -p "../Headers/glib-2.0/glib/deprecated"
mkdir -p "../Headers/glib-2.0/gobject"
# TODO: Use glib-public-headers.txt and etc for Headers
cp "Sources/glib-${GLIB_VERSION}/build/glib/glibconfig.h" "${MY_PATH}/../../Headers/"
cp "${MY_PATH}/../Sources/glib-${GLIB_VERSION}/build/gobject/glib-enumtypes.h" "${MY_PATH}/../../Headers/glib-2.0/gobject/glib-enumtypes.h"
cd "Sources/glib-${GLIB_VERSION}/glib"
cp "glib-object.h" "glib-unix.h" "glib.h" "${MY_PATH}/../../Headers/glib-2.0/"
cp *.h "${MY_PATH}/../../Headers/glib-2.0/glib/"
cd "deprecated"
cp *.h "${MY_PATH}/../../Headers/glib-2.0/glib/deprecated/"
cd "../../gio"
cp *.h "${MY_PATH}/../../Headers/glib-2.0/gio/"
cd "../gmodule"
cp "gmodule.h" "${MY_PATH}/../../Headers/glib-2.0/"
cd "../gobject"
cp *.h "${MY_PATH}/../../Headers/glib-2.0/gobject/"
cd "${MY_PATH}/../"
rm -rf "../lib/libglib-2.0.0.dylib" "../lib/libgmodule-2.0.0.dylib" "../lib/libgobject-2.0.0.dylib" "../lib/libgthread-2.0.0.dylib"
cp -rf "CompiledLibs/glib-${GLIB_VERSION}-RELEASE/"* "../lib/"
echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo