#!/usr/bin/env bash
#
# graphite2_build
# Martin Hrubý (hrubymar10), 2018
#

GRAPHITE2_VERSION="1.3.11"

edit_dylib_deps() {
        DYLIB=$1
        DEPS=$(otool -L ${DYLIB} | awk '{print $1;}' | tail -n +2)

        for DEP in $DEPS; do
                DEP_BASE=$(basename ${DEP})
                if [ "$DEP_BASE" == "$(basename $DYLIB)" ]; then
                        continue
                fi
                # Is this our redistributable file?
                if [ -f $(dirname ${DYLIB})/${DEP_BASE} ]; then
                        install_name_tool -change "${DEP}" "@loader_path/${DEP_BASE}" ${DYLIB}
                fi
        done
}

time_interval_to_string() {
        local START=$1
        local END=$2

        declare -i timestamp
        declare -i days
        declare -i hours
        declare -i minutes
        declare -i seconds
        timestamp=$END-$START

        days=$timestamp/60/60/24
        hours=$((($timestamp-($days*60*60*24))/60/60))
        minutes=$((($timestamp-($days*60*60*24)-($hours*60*60))/60))
        seconds=$((($timestamp-($days*60*60*24)-($hours*60*60)-($minutes*60))))
        if [ $days -eq 0 ]; then
        if [ $hours -eq 0 ]; then
                if [ $minutes -eq 0 ]; then
                echo "==> Operation took $seconds seconds ..."
                else
                echo "==> Operation took $minutes minutes and $seconds seconds ..."
                fi
        else
                echo "==> Operation took $hours hours $minutes minutes and $seconds seconds ..."
        fi
        else
        echo "==> Operation took $days days $hours hours $minutes minutes and $seconds seconds ..."
        fi
}

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname $0` && pwd)
if [ -z "$MY_PATH" ] ; then
        # error; for some reason, the path is not accessible
        # to the script (e.g. permissions re-evaled after suid)
        echo 'Error: Script path is for some reason not accessible' >&2
        exit 1  # fail
fi
cd "$MY_PATH"/../Sources

if ! [ -x "$(command -v wget)" ]; then
        echo 'Error: wget is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
        exit 1
fi

if xcode-select --install 2>&1 | grep installed; then
        echo "==> Xcode Command Line Tools are installed..."
else
        echo "==> Xcode Command Line Tools aren't installed, installing..."
        xcode-select --install
fi

# TODO: use cmake from MacCompileStuff
if ! [ -x "$(command -v cmake)" ]; then
        echo 'Error: cmake is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
        exit 1
fi

# TODO: Verify checksum
rm -rf graphite2-*
wget "https://github.com/silnrsi/graphite/releases/download/$GRAPHITE2_VERSION/graphite2-$GRAPHITE2_VERSION.tgz"
tar xf "graphite2-$GRAPHITE2_VERSION.tgz"
rm "graphite2-$GRAPHITE2_VERSION.tgz"
cd "graphite2-$GRAPHITE2_VERSION"
cmake .
make
mkdir "graphite2-$GRAPHITE2_VERSION-RELEASE"
cp "src/libgraphite2.3.0.1.dylib" "graphite2-$GRAPHITE2_VERSION-RELEASE/libgraphite2.3.dylib"
cd "graphite2-$GRAPHITE2_VERSION-RELEASE"
install_name_tool -id "@executable_path/../Frameworks/libgraphite2.3.dylib" "libgraphite2.3.dylib"
edit_dylib_deps libgraphite2.3.dylib
install_name_tool -change "$MY_PATH/src/libgraphite2.3.dylib" "@loader_path/libgraphite2.3.dylib" "libgraphite2.3.dylib"
cd "$MY_PATH"/../
rm -rf CompiledLibs/graphite2-*
mv "Sources/graphite2-$GRAPHITE2_VERSION/graphite2-$GRAPHITE2_VERSION-RELEASE" "CompiledLibs/graphite2-$GRAPHITE2_VERSION-RELEASE"
rm -rf ../lib/libgraphite2.3.dylib
cp -rf "CompiledLibs/graphite2-$GRAPHITE2_VERSION-RELEASE/libgraphite2.3.dylib" "../lib/libgraphite2.3.dylib"
echo "==> DONE ..."
echo
time_interval_to_string "$starttimestamp" "$(date +%s)"
echo