#!/usr/bin/env bash
#
# graphite2_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

GRAPHITE2_VERSION="1.3.14"
SHA256="f99d1c13aa5fa296898a181dff9b82fb25f6cc0933dbaa7a475d8109bd54209d"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode
check_cmake

cd "${SOURCES_PATH}"
rm -rf "graphite2"*
get_src_and_verify_checksum "graphite2-${GRAPHITE2_VERSION}.tgz" "${SHA256}" "https://github.com/silnrsi/graphite/releases/download/${GRAPHITE2_VERSION}/graphite2-${GRAPHITE2_VERSION}.tgz"
tar xf "${SOURCES_PATH}/archives/graphite2-${GRAPHITE2_VERSION}.tgz" -C .
ln -s "graphite2-${GRAPHITE2_VERSION}" "graphite2"
cd "graphite2"
cmake .
make
mkdir "graphite2-${GRAPHITE2_VERSION}-RELEASE"
cp "src/libgraphite2.3.2.1.dylib" "graphite2-${GRAPHITE2_VERSION}-RELEASE/libgraphite2.3.dylib"
cd "graphite2-${GRAPHITE2_VERSION}-RELEASE"
install_name_tool -id "@rpath/libgraphite2.3.dylib" "libgraphite2.3.dylib"
edit_dylib_deps "libgraphite2.3.dylib"
rm -rf "${LIBS_PATH}/libgraphite2.3.dylib" "${LIBS_PATH}/libgraphite2.dylib"
cp -rf "libgraphite2.3.dylib" "${LIBS_PATH}/libgraphite2.3.dylib"
ln -s "libgraphite2.3.dylib" "${LIBS_PATH}/libgraphite2.dylib"
echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo