#!/usr/bin/env bash
#
# harfbuzz_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

HARFBUZZ_VERSION="2.7.1"
SHA256="e95ee43b6bd0d3d1307e2aacf0f9c0050e5baceb21988b367b833028114aa569"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"
unset MACOSX_DEPLOYMENT_TARGET

check_wget
check_xcode
check_meson
check_ninja
check_libffi
check_glib
check_gettext
check_freetype
check_graphite2

cd "${SOURCES_PATH}"
rm -rf "harfbuzz"*
get_src_and_verify_checksum "harfbuzz-${HARFBUZZ_VERSION}.tar.xz" "${SHA256}" "https://github.com/harfbuzz/harfbuzz/releases/download/${HARFBUZZ_VERSION}/harfbuzz-${HARFBUZZ_VERSION}.tar.xz"
tar xf "${SOURCES_PATH}/archives/harfbuzz-${HARFBUZZ_VERSION}.tar.xz" -C .
ln -s "harfbuzz-${HARFBUZZ_VERSION}" "harfbuzz"
cd "harfbuzz"
mkdir "build"
meson -Dgraphite=enabled -Dcoretext=enabled --buildtype=release --default-library=shared . "build"
cd "build"
ninja
mkdir "harfbuzz-${HARFBUZZ_VERSION}-RELEASE"
cp "src/libharfbuzz.0.dylib" "harfbuzz-${HARFBUZZ_VERSION}-RELEASE/libharfbuzz.0.dylib"
cd "harfbuzz-${HARFBUZZ_VERSION}-RELEASE"
install_name_tool -id "@rpath/libharfbuzz.0.dylib" "libharfbuzz.0.dylib"
edit_dylib_deps "libharfbuzz.0.dylib"
remove_rpath_if_exists "libharfbuzz.0.dylib" "/usr/local/opt/freetype/lib"
remove_rpath_if_exists "libharfbuzz.0.dylib" "/usr/local/Cellar/graphite2/"
rm -rf "${LIBS_PATH}/libharfbuzz.0.dylib" "${LIBS_PATH}/libharfbuzz.dylib"
cp -rf "libharfbuzz.0.dylib" "${LIBS_PATH}/libharfbuzz.0.dylib"
ln -s "libharfbuzz.0.dylib" "${LIBS_PATH}/libharfbuzz.dylib"
rm -rf "${HEADERS_PATH}/harfbuzz"
mkdir "${HEADERS_PATH}/harfbuzz"
cd "${SOURCES_PATH}/harfbuzz/src"
cp "hb-blob.h" "hb-buffer.h" "hb-common.h" "hb-deprecated.h" "hb-draw.h" "hb-face.h" "hb-font.h" "hb-map.h" "hb-set.h" "hb-shape-plan.h" "hb-shape.h" "hb-style.h" "hb-unicode.h" "hb-version.h" "hb.h" "${HEADERS_PATH}/harfbuzz/"
echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo