#!/usr/bin/env bash
#
# libffi_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

LIBFFI_VERSION="3.3"
SHA256="72fba7922703ddfa7a028d513ac15a85c8d54c8d67f55fa5a4802885dc652056"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi
cd "${MY_PATH}/../Sources"

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode

rm -rf "libffi-"*
get_src_and_verify_checksum "libffi-${LIBFFI_VERSION}.tar.gz" "${SHA256}" "https://sourceware.org/pub/libffi/libffi-${LIBFFI_VERSION}.tar.gz"
tar xf "${MY_PATH}/../Sources/archives/libffi-${LIBFFI_VERSION}.tar.gz" -C .
cd "libffi-${LIBFFI_VERSION}"
./configure --disable-dependency-tracking --enable-shared
make
mkdir "libffi-${LIBFFI_VERSION}-RELEASE"
cp "x86_64-apple-darwin"*"/.libs/libffi.7.dylib" "libffi-${LIBFFI_VERSION}-RELEASE/libffi.7.dylib"
cd "libffi-${LIBFFI_VERSION}-RELEASE"
install_name_tool -id "@rpath/libffi.7.dylib" "libffi.7.dylib"
edit_dylib_deps "libffi.7.dylib"
cd "${MY_PATH}/../"
rm -rf "CompiledLibs/libffi-"*
mv "Sources/libffi-${LIBFFI_VERSION}/libffi-${LIBFFI_VERSION}-RELEASE" "CompiledLibs/libffi-${LIBFFI_VERSION}-RELEASE"
rm -rf "../lib/libffi.7.dylib"
cp -rf "CompiledLibs/libffi-${LIBFFI_VERSION}-RELEASE/libffi.7.dylib" "../lib/libffi.7.dylib"
echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo