#!/usr/bin/env bash
#
# libogg_build
# Martin Hrubý (hrubymar10), 2019-2024
#

set -e

LIBOGG_VERSION="1.3.5"
SHA256="0eb4b4b9420a0f51db142ba3f9c64b333f826532dc0f48c6410ae51f4799b664"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_pkg_config

cd "${SOURCES_PATH}"
rm -rf "libogg"*
get_src_and_verify_checksum "libogg-${LIBOGG_VERSION}.tar.gz" "${SHA256}" "https://downloads.xiph.org/releases/ogg/libogg-${LIBOGG_VERSION}.tar.gz"
tar xf "${SOURCES_PATH}/archives/libogg-${LIBOGG_VERSION}.tar.gz" -C .
cp -R "libogg-${LIBOGG_VERSION}" "libogg-${LIBOGG_VERSION}-arm64"
mv "libogg-${LIBOGG_VERSION}" "libogg-${LIBOGG_VERSION}-x86_64"
ln -s "libogg-${LIBOGG_VERSION}-x86_64" "libogg"

# Build x86_64
cd "${SOURCES_PATH}/libogg-${LIBOGG_VERSION}-x86_64"
source "${MY_PATH}/env"
export LDFLAGS="${LDFLAGS_X86_64}"
export CFLAGS="${CFLAGS_X86_64}"
export CXXFLAGS="${CXXFLAGS_X86_64}"
./configure --disable-dependency-tracking --enable-shared --host=x86_64-apple-darwin
make

# Build arm64
cd "${SOURCES_PATH}/libogg-${LIBOGG_VERSION}-arm64"
source "${MY_PATH}/env"
export LDFLAGS="${LDFLAGS_ARM64}"
export CFLAGS="${CFLAGS_ARM64}"
export CXXFLAGS="${CXXFLAGS_ARM64}"
./configure --disable-dependency-tracking --enable-shared --host=aarch64-apple-darwin
make

mkdir "libogg-${LIBOGG_VERSION}-RELEASE"
cd "libogg-${LIBOGG_VERSION}-RELEASE"
lipo -create "${SOURCES_PATH}/libogg-${LIBOGG_VERSION}-arm64/src/.libs/libogg.0.dylib" "${SOURCES_PATH}/libogg-${LIBOGG_VERSION}-x86_64/src/.libs/libogg.0.dylib" -output "libogg.0.dylib"
install_name_tool -id "@rpath/libogg.0.dylib" "libogg.0.dylib"
rm -rf "${LIBS_PATH}/libogg.0.dylib" "${LIBS_PATH}/libogg.dylib"
cp "libogg.0.dylib" "${LIBS_PATH}/libogg.0.dylib"
ln -s "libogg.0.dylib" "${LIBS_PATH}/libogg.dylib"
rm -rf "${HEADERS_PATH}/ogg"
mkdir "${HEADERS_PATH}/ogg"
cp -rf "${SOURCES_PATH}/libogg/include/ogg/"*.h "${HEADERS_PATH}/ogg/"
generate_pkgconfig_file "ogg" "${LIBOGG_VERSION}"
echo "==> DONE ..."
echo ""
