#!/usr/bin/env bash
#
# libogg_build
# Martin Hrubý (hrubymar10), 2019-2020
#

set -e

LIBOGG_VERSION="1.3.4"
SHA256="fe5670640bd49e828d64d2879c31cb4dde9758681bb664f9bdbf159a01b0c76e"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode

cd "${SOURCES_PATH}"
rm -rf "libogg"*
get_src_and_verify_checksum "libogg-${LIBOGG_VERSION}.tar.gz" "${SHA256}" "https://downloads.xiph.org/releases/ogg/libogg-${LIBOGG_VERSION}.tar.gz"
tar xf "${SOURCES_PATH}/archives/libogg-${LIBOGG_VERSION}.tar.gz" -C .
ln -s "libogg-${LIBOGG_VERSION}" "libogg"
cd "libogg"
./configure --disable-dependency-tracking --enable-shared
make
mkdir "libogg-${LIBOGG_VERSION}-RELEASE"
cp "src/.libs/libogg.0.dylib" "libogg-${LIBOGG_VERSION}-RELEASE/libogg.0.dylib"
cd "libogg-${LIBOGG_VERSION}-RELEASE"
install_name_tool -id "@rpath/libogg.0.dylib" "libogg.0.dylib"
edit_dylib_deps "libogg.0.dylib"
rm -rf "${LIBS_PATH}/libogg.0.dylib" "${LIBS_PATH}/libogg.dylib"
cp "libogg.0.dylib" "${LIBS_PATH}/libogg.0.dylib"
ln -s "libogg.0.dylib" "${LIBS_PATH}/libogg.dylib"
rm -rf "${HEADERS_PATH}/ogg"
mkdir "${HEADERS_PATH}/ogg"
cp -rf "${SOURCES_PATH}/libogg/include/ogg/"*.h "${HEADERS_PATH}/ogg/"
echo "==> DONE ..."
echo