#!/usr/bin/env bash
#
# libpng_build
# Martin Hrubý (hrubymar10), 2018
#

LIBPNG_VERSION="1.6.34"

edit_dylib_deps() {
        DYLIB=$1
        DEPS=$(otool -L ${DYLIB} | awk '{print $1;}' | tail -n +2)

        for DEP in $DEPS; do
                DEP_BASE=$(basename ${DEP})
                if [ "$DEP_BASE" == "$(basename $DYLIB)" ]; then
                        continue
                fi
                # Is this our redistributable file?
                if [ -f $(dirname ${DYLIB})/${DEP_BASE} ]; then
                        install_name_tool -change "${DEP}" "@loader_path/${DEP_BASE}" ${DYLIB}
                fi
        done
}

time_interval_to_string() {
        local START=$1
        local END=$2

        declare -i timestamp
        declare -i days
        declare -i hours
        declare -i minutes
        declare -i seconds
        timestamp=$END-$START

        days=$timestamp/60/60/24
        hours=$((($timestamp-($days*60*60*24))/60/60))
        minutes=$((($timestamp-($days*60*60*24)-($hours*60*60))/60))
        seconds=$((($timestamp-($days*60*60*24)-($hours*60*60)-($minutes*60))))
        if [ $days -eq 0 ]; then
        if [ $hours -eq 0 ]; then
                if [ $minutes -eq 0 ]; then
                echo "==> Operation took $seconds seconds ..."
                else
                echo "==> Operation took $minutes minutes and $seconds seconds ..."
                fi
        else
                echo "==> Operation took $hours hours $minutes minutes and $seconds seconds ..."
        fi
        else
        echo "==> Operation took $days days $hours hours $minutes minutes and $seconds seconds ..."
        fi
}

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname $0` && pwd)
if [ -z "$MY_PATH" ] ; then
        # error; for some reason, the path is not accessible
        # to the script (e.g. permissions re-evaled after suid)
        echo 'Error: Script path is for some reason not accessible' >&2
        exit 1  # fail
fi
cd "$MY_PATH"/../Sources

if ! [ -x "$(command -v wget)" ]; then
        echo 'Error: wget is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
        exit 1
fi

if xcode-select --install 2>&1 | grep installed; then
        echo "==> Xcode Command Line Tools are installed..."
else
        echo "==> Xcode Command Line Tools aren't installed, installing..."
        xcode-select --install
fi

# TODO: Verify checksum
rm -rf libpng-*
wget "http://prdownloads.sourceforge.net/libpng/libpng-$LIBPNG_VERSION.tar.xz?download" -O "libpng-$LIBPNG_VERSION.tar.xz"
tar xf "libpng-$LIBPNG_VERSION.tar.xz"
rm "libpng-$LIBPNG_VERSION.tar.xz"
cd "libpng-$LIBPNG_VERSION"
./configure --disable-dependency-tracking --enable-shared
make check
mkdir "libpng-$LIBPNG_VERSION-RELEASE"
cp ".libs/libpng16.16.dylib" "libpng-$LIBPNG_VERSION-RELEASE/libpng16.16.dylib"
cd "libpng-$LIBPNG_VERSION-RELEASE"
install_name_tool -id "@executable_path/../Frameworks/libpng16.16.dylib" "libpng16.16.dylib"
edit_dylib_deps libpng16.16.dylib
cd "$MY_PATH"/../
rm -rf CompiledLibs/libpng-*
mv "Sources/libpng-$LIBPNG_VERSION/libpng-$LIBPNG_VERSION-RELEASE" "CompiledLibs/libpng-$LIBPNG_VERSION-RELEASE"
rm -rf ../Headers/png*
cp "Sources/libpng-$LIBPNG_VERSION/png.h" ../Headers/png.h
cp "Sources/libpng-$LIBPNG_VERSION/pngconf.h" ../Headers/pngconf.h
cp "Sources/libpng-$LIBPNG_VERSION/pnglibconf.h" ../Headers/pnglibconf.h
rm -rf ../lib/libpng16.16.dylib
cp -rf "CompiledLibs/libpng-$LIBPNG_VERSION-RELEASE/libpng16.16.dylib" "../lib/libpng16.16.dylib"
echo "==> DONE ..."
echo
time_interval_to_string "$starttimestamp" "$(date +%s)"
echo