#!/usr/bin/env bash
#
# libpng_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

LIBPNG_VERSION="1.6.37"
SHA256="505e70834d35383537b6491e7ae8641f1a4bed1876dbfe361201fc80868d88ca"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi
cd "${MY_PATH}/../Sources"

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode

rm -rf "libpng-"*
get_src_and_verify_checksum "libpng-${LIBPNG_VERSION}.tar.xz" "${SHA256}" "http://prdownloads.sourceforge.net/libpng/libpng-${LIBPNG_VERSION}.tar.xz?download" -O "libpng-${LIBPNG_VERSION}.tar.xz"
tar xf "${MY_PATH}/../Sources/archives/libpng-${LIBPNG_VERSION}.tar.xz" -C .
cd "libpng-${LIBPNG_VERSION}"
./configure --disable-dependency-tracking --enable-shared
make check
mkdir "libpng-${LIBPNG_VERSION}-RELEASE"
cp ".libs/libpng16.16.dylib" "libpng-${LIBPNG_VERSION}-RELEASE/libpng16.16.dylib"
cd "libpng-${LIBPNG_VERSION}-RELEASE"
install_name_tool -id "@rpath/libpng16.16.dylib" "libpng16.16.dylib"
edit_dylib_deps "libpng16.16.dylib"
cd "${MY_PATH}/../"
rm -rf "CompiledLibs/libpng-"*
mv "Sources/libpng-${LIBPNG_VERSION}/libpng-${LIBPNG_VERSION}-RELEASE" "CompiledLibs/libpng-${LIBPNG_VERSION}-RELEASE"
rm -rf "../lib/libpng16.16.dylib"
cp -rf "CompiledLibs/libpng-${LIBPNG_VERSION}-RELEASE/libpng16.16.dylib" "../lib/libpng16.16.dylib"
echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo