#!/usr/bin/env bash
#
# libvorbis_build
# Martin Hrubý (hrubymar10), 2019-2020
#

set -e

LIBVORBIS_VERSION="1.3.7"
SHA256="b33cc4934322bcbf6efcbacf49e3ca01aadbea4114ec9589d1b1e9d20f72954b"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi
cd "${MY_PATH}/../Sources"

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode
check_libogg

rm -rf "libvorbis-"*
get_src_and_verify_checksum "libvorbis-${LIBVORBIS_VERSION}.tar.xz" "${SHA256}" "http://downloads.xiph.org/releases/vorbis/libvorbis-${LIBVORBIS_VERSION}.tar.xz"
tar xf "${MY_PATH}/../Sources/archives/libvorbis-${LIBVORBIS_VERSION}.tar.xz" -C .
cd "libvorbis-${LIBVORBIS_VERSION}"
./configure --disable-dependency-tracking --enable-shared
make
mkdir "libvorbis-${LIBVORBIS_VERSION}-RELEASE"
cp "lib/.libs/libvorbis.0.dylib" "libvorbis-${LIBVORBIS_VERSION}-RELEASE/libvorbis.0.dylib"
cp "lib/.libs/libvorbisfile.3.dylib" "libvorbis-${LIBVORBIS_VERSION}-RELEASE/libvorbisfile.dylib"
cd "libvorbis-${LIBVORBIS_VERSION}-RELEASE"
install_name_tool -id "@rpath/libvorbis.0.dylib" "libvorbis.0.dylib"
install_name_tool -id "@rpath/libvorbisfile.dylib" "libvorbisfile.dylib"
edit_dylib_deps "libvorbis.0.dylib"
edit_dylib_deps "libvorbisfile.dylib"
cd "${MY_PATH}"/../
rm -rf "CompiledLibs/libvorbis-"*
mv "Sources/libvorbis-${LIBVORBIS_VERSION}/libvorbis-${LIBVORBIS_VERSION}-RELEASE" "CompiledLibs/libvorbis-${LIBVORBIS_VERSION}-RELEASE"
rm -rf "../lib/libvorbis"*
cp -rf "CompiledLibs/libvorbis-${LIBVORBIS_VERSION}-RELEASE/libvorbis.0.dylib" "../lib/libvorbis.0.dylib"
cp -rf "CompiledLibs/libvorbis-${LIBVORBIS_VERSION}-RELEASE/libvorbisfile.dylib" "../lib/libvorbisfile.dylib"
rm -rf "../Headers/vorbis"
mkdir "../Headers/vorbis"
cp -rf "Sources/libvorbis-${LIBVORBIS_VERSION}/include/vorbis/"*.h "../Headers/vorbis/"
echo "==> DONE ..."
echo