#!/usr/bin/env bash
#
# libvorbis_build
# Martin Hrubý (hrubymar10), 2019-2022
#

set -e

LIBVORBIS_VERSION="1.3.7"
SHA256="b33cc4934322bcbf6efcbacf49e3ca01aadbea4114ec9589d1b1e9d20f72954b"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_libogg

cd "${SOURCES_PATH}"
rm -rf "libvorbis"*
get_src_and_verify_checksum "libvorbis-${LIBVORBIS_VERSION}.tar.xz" "${SHA256}" "http://downloads.xiph.org/releases/vorbis/libvorbis-${LIBVORBIS_VERSION}.tar.xz"
tar xf "${SOURCES_PATH}/archives/libvorbis-${LIBVORBIS_VERSION}.tar.xz" -C .
cp -R "libvorbis-${LIBVORBIS_VERSION}" "libvorbis-${LIBVORBIS_VERSION}-arm64"
ln -s "libvorbis-${LIBVORBIS_VERSION}" "libvorbis"
cd "libvorbis"
# Build x86_64
source "${MY_PATH}/env"
export LDFLAGS="${LDFLAGS_X86_64}"
export CFLAGS="${CFLAGS_X86_64}"
export CXXFLAGS="${CXXFLAGS_X86_64}"
./configure --disable-dependency-tracking --enable-shared --host=x86_64-apple-darwin
make
# Build arm64
cd "${SOURCES_PATH}/libvorbis-${LIBVORBIS_VERSION}-arm64"
source "${MY_PATH}/env"
export LDFLAGS="${LDFLAGS_ARM64}"
export CFLAGS="${CFLAGS_ARM64}"
export CXXFLAGS="${CXXFLAGS_ARM64}"
./configure --disable-dependency-tracking --enable-shared --host=aarch64-apple-darwin
make
mkdir "libvorbis-${LIBVORBIS_VERSION}-RELEASE"
cd "libvorbis-${LIBVORBIS_VERSION}-RELEASE"
lipo -create "${SOURCES_PATH}/libvorbis-${LIBVORBIS_VERSION}-arm64/lib/.libs/libvorbis.0.dylib" "${SOURCES_PATH}/libvorbis-${LIBVORBIS_VERSION}/lib/.libs/libvorbis.0.dylib" -output "libvorbis.0.dylib"
lipo -create "${SOURCES_PATH}/libvorbis-${LIBVORBIS_VERSION}-arm64/lib/.libs/libvorbisfile.dylib" "${SOURCES_PATH}/libvorbis-${LIBVORBIS_VERSION}/lib/.libs/libvorbisfile.dylib" -output "libvorbisfile.dylib"
for filename in * ; do
  install_name_tool -id "@rpath/${filename}" "${filename}"
  install_name_tool -change "/usr/local/lib/libvorbis.0.dylib" "@loader_path/libvorbis.0.dylib" "${filename}"
done
rm -rf "${LIBS_PATH}/libvorbis.0.dylib" "${LIBS_PATH}/libvorbis.dylib" "${LIBS_PATH}/libvorbisfile.dylib"
cp -rf "libvorbis.0.dylib" "${LIBS_PATH}/libvorbis.0.dylib"
cp -rf "libvorbisfile.dylib" "${LIBS_PATH}/libvorbisfile.dylib"
ln -s "libvorbis.0.dylib" "${LIBS_PATH}/libvorbis.dylib"
rm -rf "${HEADERS_PATH}/vorbis"
mkdir "${HEADERS_PATH}/vorbis"
cp -rf "${SOURCES_PATH}/libvorbis/include/vorbis/"*.h "${HEADERS_PATH}/vorbis/"
echo "==> DONE ..."
echo ""
