#!/usr/bin/env bash
#
# libvorbis_build
# Martin Hrubý (hrubymar10), 2019-2020
#

set -e

LIBVORBIS_VERSION="1.3.7"
SHA256="b33cc4934322bcbf6efcbacf49e3ca01aadbea4114ec9589d1b1e9d20f72954b"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode
check_libogg

cd "${SOURCES_PATH}"
rm -rf "libvorbis"*
get_src_and_verify_checksum "libvorbis-${LIBVORBIS_VERSION}.tar.xz" "${SHA256}" "http://downloads.xiph.org/releases/vorbis/libvorbis-${LIBVORBIS_VERSION}.tar.xz"
tar xf "${SOURCES_PATH}/archives/libvorbis-${LIBVORBIS_VERSION}.tar.xz" -C .
ln -s "libvorbis-${LIBVORBIS_VERSION}" "libvorbis"
cd "libvorbis"
./configure --disable-dependency-tracking --enable-shared
make
mkdir "libvorbis-${LIBVORBIS_VERSION}-RELEASE"
cp "lib/.libs/libvorbis.0.dylib" "libvorbis-${LIBVORBIS_VERSION}-RELEASE/libvorbis.0.dylib"
cp "lib/.libs/libvorbisfile.3.dylib" "libvorbis-${LIBVORBIS_VERSION}-RELEASE/libvorbisfile.dylib"
cd "libvorbis-${LIBVORBIS_VERSION}-RELEASE"
install_name_tool -id "@rpath/libvorbis.0.dylib" "libvorbis.0.dylib"
install_name_tool -id "@rpath/libvorbisfile.dylib" "libvorbisfile.dylib"
edit_dylib_deps "libvorbis.0.dylib"
edit_dylib_deps "libvorbisfile.dylib"
rm -rf "${LIBS_PATH}/libvorbis.0.dylib" "${LIBS_PATH}/libvorbis.dylib" "${LIBS_PATH}/libvorbisfile.dylib"
cp -rf "libvorbis.0.dylib" "${LIBS_PATH}/libvorbis.0.dylib"
cp -rf "libvorbisfile.dylib" "${LIBS_PATH}/libvorbisfile.dylib"
ln -s "libvorbis.0.dylib" "${LIBS_PATH}/libvorbis.dylib"
rm -rf "${HEADERS_PATH}/vorbis"
mkdir "${HEADERS_PATH}/vorbis"
cp -rf "${SOURCES_PATH}/libvorbis/include/vorbis/"*.h "${HEADERS_PATH}/vorbis/"
echo "==> DONE ..."
echo