#!/usr/bin/env bash
#
# pango_build
# Martin Hrubý (hrubymar10), 2018-2024
#

set -e

PANGO_VERSION="1.55.0"
PANGO_VERSION_SHORT="1.55"
SHA256="a2c17a8dc459a7267b8b167bb149d23ff473b6ff9d5972bee047807ee2220ccf"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"
unset MACOSX_DEPLOYMENT_TARGET

check_wget
check_libffi
check_glib
check_cairo
check_gettext
check_harfbuzz
check_fontconfig
check_freetype
check_fribidi
check_meson
check_ninja
check_pkg_config

if ! is_apple_silicon_mac; then
  echo "Error: Pango requires Apple Silicon mac to build universal libs" >&2
  exit 1
fi

cd "${SOURCES_PATH}"
rm -rf "pango"*
get_src_and_verify_checksum "pango-${PANGO_VERSION}.tar.xz" "${SHA256}" "http://ftp.gnome.org/pub/GNOME/sources/pango/${PANGO_VERSION_SHORT}/pango-${PANGO_VERSION}.tar.xz"
tar xf "${SOURCES_PATH}/archives/pango-${PANGO_VERSION}.tar.xz" -C .
cp -R "pango-${PANGO_VERSION}" "pango-${PANGO_VERSION}-arm64"
mv "pango-${PANGO_VERSION}" "pango-${PANGO_VERSION}-x86_64"
ln -s "pango-${PANGO_VERSION}-x86_64" "pango"

# Build x86_64
cd "${SOURCES_PATH}/pango-${PANGO_VERSION}-x86_64"
source "${MY_PATH}/env"
patch -b -p0 < "${SCRIPTS_PATH}/pango.patch"
unset MACOSX_DEPLOYMENT_TARGET
export LDFLAGS="${LDFLAGS_X86_64}"
export CFLAGS="${CFLAGS_X86_64}"
export CXXFLAGS="${CXXFLAGS_X86_64}"
mkdir "build"
sed -i -e "/-Werror=unused-but-set-variable/d" "meson.build"
arch -x86_64 /opt/homebrew_x86_64/bin/meson setup -Dintrospection=disabled -Djson-glib:introspection=disabled -Djson-glib:tests=false -Dfontconfig=enabled -Dcairo=enabled -Dfreetype=enabled --default-library=shared --buildtype=release --wrap-mode=nofallback . "build"
arch -x86_64 /opt/homebrew_x86_64/bin/meson compile -C build --verbose

# Build arm64
cd "${SOURCES_PATH}/pango-${PANGO_VERSION}-arm64"
source "${MY_PATH}/env"
patch -b -p0 < "${SCRIPTS_PATH}/pango.patch"
unset MACOSX_DEPLOYMENT_TARGET
export LDFLAGS="${LDFLAGS_ARM64}"
export CFLAGS="${CFLAGS_ARM64}"
export CXXFLAGS="${CXXFLAGS_ARM64}"
mkdir "build"
arch -arm64 /opt/homebrew/bin/meson setup -Dintrospection=disabled -Djson-glib:introspection=disabled -Djson-glib:tests=false -Dfontconfig=enabled -Dcairo=enabled -Dfreetype=enabled --default-library=shared --buildtype=release --wrap-mode=nofallback . "build"
arch -arm64 /opt/homebrew/bin/meson compile -C build --verbose

mkdir "pango-${PANGO_VERSION}-RELEASE"
cd "pango-${PANGO_VERSION}-RELEASE"
lipo -create "${SOURCES_PATH}/pango-${PANGO_VERSION}-arm64/build/pango/libpango-1.0.0.dylib" "${SOURCES_PATH}/pango-${PANGO_VERSION}-x86_64/build/pango/libpango-1.0.0.dylib" -output "libpango-1.0.0.dylib"
lipo -create "${SOURCES_PATH}/pango-${PANGO_VERSION}-arm64/build/pango/libpangocairo-1.0.0.dylib" "${SOURCES_PATH}/pango-${PANGO_VERSION}-x86_64/build/pango/libpangocairo-1.0.0.dylib" -output "libpangocairo-1.0.0.dylib"
lipo -create "${SOURCES_PATH}/pango-${PANGO_VERSION}-arm64/build/pango/libpangoft2-1.0.0.dylib" "${SOURCES_PATH}/pango-${PANGO_VERSION}-x86_64/build/pango/libpangoft2-1.0.0.dylib" -output "libpangoft2-1.0.0.dylib"
for filename in * ; do
  install_name_tool -id "@rpath/${filename}" "${filename}"
    remove_rpath_if_exists "${filename}" "@loader_path/"
  remove_rpath_if_exists "${filename}" "${LIBS_PATH}"
done
rm -rf "${LIBS_PATH}/libpango"*
cp -rf * "${LIBS_PATH}/"
rm -rf "${HEADERS_PATH}/pango"
mkdir "${HEADERS_PATH}/pango"
cp "${SOURCES_PATH}/pango/build/pango/pango-enum-types.h" "${HEADERS_PATH}/pango/"
cp "${SOURCES_PATH}/pango/build/pango/pango-features.h" "${HEADERS_PATH}/pango/"
cd "${SOURCES_PATH}/pango/pango"
cp "pango-attributes.h" "pango-bidi-type.h" "pango-break.h" "pango-color.h" "pango-context.h" "pango-coverage.h" "pango-engine.h" "pango-font.h" "pango-fontmap.h" "pango-fontset.h" "pango-fontset-simple.h" "pango-glyph-item.h" "pango-glyph.h" "pango-gravity.h" "pango-item.h" "pango-language.h" "pango-layout.h" "pango-markup.h" "pango-matrix.h" "pango-modules.h" "pango-ot.h" "pango-renderer.h" "pango-script.h" "pango-tabs.h" "pango-types.h" "pango-utils.h" "pango.h" "pangocairo.h" "pangofc-decoder.h" "pangofc-font.h" "pangofc-fontmap.h" "pangoft2.h" "pangoxft-render.h" "pangoxft.h" "pango-version-macros.h" "pango-direction.h" "${HEADERS_PATH}/pango/"
generate_pkgconfig_file "pango" "${PANGO_VERSION}"
generate_pkgconfig_file "pangocairo" "${PANGO_VERSION}"
generate_pkgconfig_file "pangofc" "${PANGO_VERSION}"
generate_pkgconfig_file "pangoft2" "${PANGO_VERSION}"
generate_pkgconfig_file "pangoot" "${PANGO_VERSION}"
echo "==> DONE ..."
echo ""
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo ""
