#!/usr/bin/env bash
#
# pcre_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

PCRE_VERSION="8.44"
SHA256="19108658b23b3ec5058edc9f66ac545ea19f9537234be1ec62b714c84399366d"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_gettext
check_fontconfig
check_freetype

cd "${SOURCES_PATH}"
rm -rf "pcre"*
get_src_and_verify_checksum "pcre-${PCRE_VERSION}.tar.bz2" "${SHA256}" "https://ftp.pcre.org/pub/pcre/pcre-${PCRE_VERSION}.tar.bz2"
tar xf "${SOURCES_PATH}/archives/pcre-${PCRE_VERSION}.tar.bz2" -C .
cp -R "pcre-${PCRE_VERSION}" "pcre-${PCRE_VERSION}-arm64"
ln -s "pcre-${PCRE_VERSION}" "pcre"
cd "pcre"
# Build x86_64
source "${MY_PATH}/env"
export LDFLAGS="${LDFLAGS_X86_64}"
export CFLAGS="${CFLAGS_X86_64}"
export CXXFLAGS="${CXXFLAGS_X86_64}"
./configure --disable-dependency-tracking --enable-utf8 --enable-pcregrep-libz --enable-pcregrep-libbz2 --enable-jit --host=x86_64-apple-darwin
make
# Build arm64
cd "${SOURCES_PATH}/pcre-${PCRE_VERSION}-arm64"
source "${MY_PATH}/env"
export LDFLAGS="${LDFLAGS_ARM64}"
export CFLAGS="${CFLAGS_ARM64}"
export CXXFLAGS="${CXXFLAGS_ARM64}"
./configure --disable-dependency-tracking --enable-utf8 --enable-pcregrep-libz --enable-pcregrep-libbz2 --enable-jit --host=aarch64-apple-darwin
make
mkdir "pcre-${PCRE_VERSION}-RELEASE"
cd "pcre-${PCRE_VERSION}-RELEASE"
lipo -create "${SOURCES_PATH}/pcre-${PCRE_VERSION}-arm64/.libs/libpcre.1.dylib" "${SOURCES_PATH}/pcre-${PCRE_VERSION}/.libs/libpcre.1.dylib" -output "libpcre.1.dylib"
install_name_tool -id "@rpath/libpcre.1.dylib" "libpcre.1.dylib"
rm -rf "${LIBS_PATH}/libpcre.1.dylib" "${LIBS_PATH}/libpcre.dylib"
cp -rf "libpcre.1.dylib" "${LIBS_PATH}/libpcre.1.dylib"
ln -s "libpcre.1.dylib" "${LIBS_PATH}/libpcre.dylib"
generate_pkgconfig_file "libpcre" "${PCRE_VERSION}"
echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo