#!/usr/bin/env bash
#
# pcre_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

PCRE_VERSION="8.44"
SHA256="19108658b23b3ec5058edc9f66ac545ea19f9537234be1ec62b714c84399366d"

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi
cd "${MY_PATH}/../Sources"

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode
check_cairo
check_glib
check_gettext
check_harfbuzz
check_fontconfig
check_freetype

rm -rf "pcre-"*
get_src_and_verify_checksum "pcre-${PCRE_VERSION}.tar.bz2" "${SHA256}" "https://ftp.pcre.org/pub/pcre/pcre-${PCRE_VERSION}.tar.bz2"
tar xf "${MY_PATH}/../Sources/archives/pcre-${PCRE_VERSION}.tar.bz2" -C .
cd "pcre-${PCRE_VERSION}"
./configure --disable-dependency-tracking --enable-utf8 --enable-pcregrep-libz --enable-pcregrep-libbz2 --enable-jit
make
mkdir "pcre-${PCRE_VERSION}-RELEASE"
cp ".libs/libpcre.1.dylib" "pcre-${PCRE_VERSION}-RELEASE/libpcre.1.dylib"
cd "pcre-${PCRE_VERSION}-RELEASE"
install_name_tool -id "@rpath/libpcre.1.dylib" "libpcre.1.dylib"
edit_dylib_deps "libpcre.1.dylib"
cd "${MY_PATH}/../"
rm -rf "CompiledLibs/pcre-"*
mv "Sources/pcre-${PCRE_VERSION}/pcre-${PCRE_VERSION}-RELEASE" "CompiledLibs/pcre-${PCRE_VERSION}-RELEASE"
rm -rf "../lib/libpcre.1.dylib"
cp -rf "CompiledLibs/pcre-${PCRE_VERSION}-RELEASE/libpcre.1.dylib" "../lib/libpcre.1.dylib"
echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo