#!/usr/bin/env bash
#
# readline_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

READLINE_VERSION="8.0"
PATCH_PREFIX="readline80"
NUM_OF_PATHES="4"
SHA256="e339f51971478d369f8a053a330a190781acb9864cf4c541060f12078948e461"
SHA256_PATCHES=(
  "d8e5e98933cf5756f862243c0601cb69d3667bb33f2c7b751fe4e40b2c3fd069"
  "36b0febff1e560091ae7476026921f31b6d1dd4c918dcb7b741aa2dad1aec8f7"
  "94ddb2210b71eb5389c7756865d60e343666dfb722c85892f8226b26bb3eeaef"
  "b1aa3d2a40eee2dea9708229740742e649c32bb8db13535ea78f8ac15377394c"
)

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode

cd "${SOURCES_PATH}"
rm -rf "readline"*
get_src_and_verify_checksum "readline-${READLINE_VERSION}.tar.gz" "${SHA256}" "https://ftp.gnu.org/gnu/readline/readline-${READLINE_VERSION}.tar.gz"
tar xf "${SOURCES_PATH}/archives/readline-${READLINE_VERSION}.tar.gz" -C .
ln -s "readline-${READLINE_VERSION}" "readline"
cd "readline"
for i in $(seq 1 ${NUM_OF_PATHES}); do
  PATCH=`printf "%03d\n" ${i}`
  get_src_and_verify_checksum "${PATCH_PREFIX}-${PATCH}" "${SHA256_PATCHES[$((${i}-1))]}" "https://ftp.gnu.org/gnu/readline/readline-${READLINE_VERSION}-patches/${PATCH_PREFIX}-${PATCH}"
  patch -b < "${SOURCES_PATH}/archives/${PATCH_PREFIX}-${PATCH}"
done
./configure --enable-shared
make shared
mkdir "readline-${READLINE_VERSION}-RELEASE"
cp -rf "shlib/libreadline.${READLINE_VERSION}.dylib" "readline-${READLINE_VERSION}-RELEASE/libreadline.${READLINE_VERSION}.dylib"
cd "readline-${READLINE_VERSION}-RELEASE"
install_name_tool -id "@rpath/libreadline.${READLINE_VERSION}.dylib" "libreadline.${READLINE_VERSION}.dylib"
edit_dylib_deps "libreadline.${READLINE_VERSION}.dylib"
rm -rf "${LIBS_PATH}/libreadline"*
cp -rf "libreadline.${READLINE_VERSION}.dylib" "${LIBS_PATH}/libreadline.${READLINE_VERSION}.dylib"
ln -s "libreadline.${READLINE_VERSION}.dylib" "${LIBS_PATH}/libreadline.dylib"
rm -rf "${HEADERS_PATH}/readline"
mkdir "${HEADERS_PATH}/readline"
cd "${SOURCES_PATH}/readline"
cp -rf "chardefs.h" "history.h" "keymaps.h" "readline.h" "rlconf.h" "rlstdc.h" "rltypedefs.h" "tilde.h" "${HEADERS_PATH}/readline/"
echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo