#!/usr/bin/env bash
#
# readline_build
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

READLINE_VERSION="8.0"
PATCH_PREFIX="readline80"
NUM_OF_PATHES="4"
SHA256="e339f51971478d369f8a053a330a190781acb9864cf4c541060f12078948e461"
SHA256_PATCHES=(
  "d8e5e98933cf5756f862243c0601cb69d3667bb33f2c7b751fe4e40b2c3fd069"
  "36b0febff1e560091ae7476026921f31b6d1dd4c918dcb7b741aa2dad1aec8f7"
  "94ddb2210b71eb5389c7756865d60e343666dfb722c85892f8226b26bb3eeaef"
  "b1aa3d2a40eee2dea9708229740742e649c32bb8db13535ea78f8ac15377394c"
)

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi
cd "${MY_PATH}/../Sources"

source "${MY_PATH}/env"
source "${MY_PATH}/functions"

check_wget
check_xcode

rm -rf "readline-"*
get_src_and_verify_checksum "readline-${READLINE_VERSION}.tar.gz" "${SHA256}" "https://ftp.gnu.org/gnu/readline/readline-${READLINE_VERSION}.tar.gz"
tar xf "${MY_PATH}/../Sources/archives/readline-${READLINE_VERSION}.tar.gz" -C .
cd "readline-${READLINE_VERSION}"
for i in $(seq 1 ${NUM_OF_PATHES}); do
  PATCH=`printf "%03d\n" ${i}`
  get_src_and_verify_checksum "${PATCH_PREFIX}-${PATCH}" "${SHA256_PATCHES[$((${i}-1))]}" "https://ftp.gnu.org/gnu/readline/readline-${READLINE_VERSION}-patches/${PATCH_PREFIX}-${PATCH}"
  patch -b < "${MY_PATH}/../Sources/archives/${PATCH_PREFIX}-${PATCH}"
done
./configure --enable-shared
make shared
mkdir "readline-${READLINE_VERSION}-RELEASE"
cp "shlib/libreadline.${READLINE_VERSION}.dylib" "readline-${READLINE_VERSION}-RELEASE/libreadline.${READLINE_VERSION}.dylib"
cd "readline-${READLINE_VERSION}-RELEASE"
install_name_tool -id "@rpath/libreadline.${READLINE_VERSION}.dylib" "libreadline.${READLINE_VERSION}.dylib"
edit_dylib_deps "libreadline.${READLINE_VERSION}.dylib"
cd ..
rm -rf "${MY_PATH}/../CompiledLibs/readline-"*
mv "${MY_PATH}/../Sources/readline-${READLINE_VERSION}/readline-${READLINE_VERSION}-RELEASE" "${MY_PATH}/../CompiledLibs/readline-${READLINE_VERSION}-RELEASE"
rm -rf "${MY_PATH}/../../Headers/readline"
mkdir "${MY_PATH}/../../Headers/readline"
cp -rf "chardefs.h" "history.h" "keymaps.h" "readline.h" "rlconf.h" "rlstdc.h" "rltypedefs.h" "tilde.h" "${MY_PATH}/../../Headers/readline/"
rm -rf "${MY_PATH}/../../lib/libreadline"*
cp -rf "${MY_PATH}/../CompiledLibs/readline-${READLINE_VERSION}-RELEASE/libreadline.${READLINE_VERSION}.dylib" "${MY_PATH}/../../lib/libreadline.${READLINE_VERSION}.dylib"

echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo