/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.30.10-g45a00138 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.30.10-g45a00138"
#endif
#define SDL_REVISION_NUMBER 0
