#!/usr/bin/env bash
#
# Build_All
# Martin Hrubý (hrubymar10), 2018-2020
#

set -e

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname ${0}` && pwd)
if [ -z "${MY_PATH}" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  echo 'Error: Script path is for some reason not accessible' >&2
  exit 1  # fail
fi
cd "${MY_PATH}/Scripts"

source "${MY_PATH}/Scripts/functions"

SCRIPTS=(
  "fribidi"
  "libogg"
  "libvorbis"
  "libffi"
  "libpng"
  "freetype"
  "SDL2"
  "gettext"
  "pixman"
  "fontconfig"
  "graphite2"
  "readline"
  "pcre"
  "boost"
  "glib"
  "cairo"
  "harfbuzz"
  "pango"
  "openssl"
)

for SCRIPT in "${SCRIPTS[@]}"; do
  echo "==> Building ${SCRIPT}"
  "./${SCRIPT}_build"
done

echo "==> DONE ..."
echo
time_interval_to_string "${starttimestamp}" "$(date +%s)"
echo